"use client";
import Head from "next/head";
import Image from "next/image";
import {
  AiFillTwitterCircle,
  AiFillLinkedin,
  AiFillGithub,
} from "react-icons/ai";
import { BsFillMoonStarsFill } from "react-icons/bs";
import { useState } from "react";
import css from "../assets/css.png";
import javascript from "../assets/javascript.png";
import react from "../assets/react.png";
import typescript from "../assets/typescript.png";
import mu5 from "../assets/mu5.png";
import redux from "../assets/redux.png";
import node from "../assets/node.png";
import html from "../assets/html.png";
import about4 from "../assets/about04.png";
import api from "../assets/api.png";
import graphql from "../assets/graphql.png";
import python from "../assets/python.png";
import git from "../assets/git.png";
import spaceman from "../assets/Spaceman-colour.svg";
import Link from "next/link";
import { motion } from "framer-motion";

const images = [
  css,
  javascript,
  react,
  typescript,
  mu5,
  redux,
  node,
  html,
  api,
  graphql,
  python,
  git,
];

const astronautTransition = {
  y: {
    repeat: Infinity,
    ease: "easeOut",
    repeatDelay: 4,
    duration: 2,
  },
};
export default function Home() {
  const [darkMode, setDarkMode] = useState(false);
  const [name, setName] = useState<string>("");
  const [email, setEmail] = useState<string>("");
  const [message, setMessage] = useState<string>("");

  const nameEl = (e: React.ChangeEvent<HTMLInputElement>) => {
    setName(e.target.value);
  };

  const emailEl = (e: React.ChangeEvent<HTMLInputElement>) => {
    setEmail(e.target.value);
  };

  const messageEl = (e: React.ChangeEvent<HTMLTextAreaElement>) => {
    setMessage(e.target.value);
  };

  return (
    <div className={darkMode ? "dark" : ""}>
      <Head>
        <title>Kibuye Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <nav className="mb-12 dark:bg-slate-800 py-4 px-10 md:px-20 lg:px-40 fixed top-0 z-10 w-full overflow-y-auto bg-[#fcfcfc] dark:text-white">
        <div className="flex justify-between">
          <h1 className="font-burtons text-xl hidden md:flex">
            <Link href="#">ki.dev</Link>
          </h1>
          <ul className="flex flex-row gap-x-8">
            <li>
              <a href="#about">About</a>
            </li>
            <li>
              <a href="#skills">Skills</a>
            </li>
            <li>
              <a href="#portfolio">Portfolio</a>
            </li>
            <li>
              <a href="#contact">Contact</a>
            </li>
            <li>
              <BsFillMoonStarsFill
                onClick={() => setDarkMode(!darkMode)}
                className=" text-sky-900 dark:text-yellow-500 cursor-pointer text-2xl"
              />
            </li>
          </ul>
        </div>
      </nav>
      <main className=" bg-white px-10 dark:bg-gray-900 md:px-20 lg:px-40">
        <section className="h-screen py-10 mt-10">
          <div>
            <div className="flex flex-col md:flex-row">
              <div className="w-full md:w-1/2">
                <h2 className="text-4xl font-bold mb-4 dark:text-white">
                  Hi,{" "}
                  <span className="dark:text-yellow-500 text-blue-700">
                    I'm Kibuye
                  </span>
                </h2>
                <p className="text-lg mb-4 dark:text-gray-300">
                  I'm a full stack developer with a passion for building
                  applications that solve real world problems. I'm currently
                  working on{" "}
                  <Link
                    className="text-sky-900 dark:text-yellow-500"
                    href="https://justavision.netlify.app"
                    target="_blank"
                  >
                    JustaVision
                  </Link>{" "}
                  as a full stack developer.
                </p>
                <p className="text-lg mb-4 dark:text-gray-300">
                  I'm also a huge fan of open source and you can look at other
                  cool projects I have on my{" "}
                  <a
                    className="text-sky-900 dark:text-yellow-500"
                    href="https://github.com/Kibuye24"
                  >
                    Github
                  </a>{" "}
                </p>
              </div>
              <motion.div
                transition={astronautTransition}
                animate={{
                  y: [0, 100, 0],
                }}
                className="w-full md:w-1/2 px-3"
              >
                <Image src={spaceman} alt="hero" width={400} height={400} />
              </motion.div>
            </div>
          </div>
        </section>
        <section id="about" className="min-h-screen">
          <div className="flex flex-col md:flex-row items-center p-3">
            <div className="w-full">
              <h2 className="text-4xl font-bold mb-4 mx-auto dark:text-white">
                The best way to predict the future is to{" "}
                <span className="dark:text-yellow-500 text-blue-700">
                  CREATE IT
                </span>
                !
              </h2>
              <p className="mb-4 mx-auto dark:text-gray-300">
                I believe that programming languages are just tools used to
                solve problems. I'm always looking for new ways to solve
                problems and I'm always open to learning new things. At the
                moment, I can help your organization with the following:
              </p>
              <div className="flex flex-col md:flex-row gap-x-3 p-10 bg-[#fcfcfc] dark:bg-slate-900 dark:text-gray-300 rounded-sm shadow-xl w-full">
                <div className="flex flex-col p-4">
                  <h3 className="font-bold dark:text-yellow-500">
                    Front-End Web Development
                  </h3>
                  <p className="text-sm dark:text-gray-300">
                    <span className="text-blue-700 dark:text-red-500">
                      Modern UI is 90% rounded divs!
                    </span>{" "}
                    I can help you build modern, responsive and performant web
                    applications using modern frameworks like React. I am
                    skilled in creating custom UI components and animations.
                  </p>
                </div>
                <div className="flex flex-col p-4">
                  <h3 className="font-bold dark:text-yellow-500">
                    Back-end Web Development
                  </h3>
                  <p className="text-sm dark:text-gray-300">
                    <span className="text-blue-700 dark:text-red-500">
                      To SQL or NoSQL? That is the query!
                    </span>{" "}
                    I write clean API's and apply the best practices such as
                    salting and hashing passwords, JWT, Cookies and Sessions,
                    and more.
                  </p>
                </div>
                <div className="flex flex-col p-4">
                  <h3 className="font-bold dark:text-yellow-500">
                    Cloud Computing
                  </h3>
                  <p className="text-sm">
                    <span className="text-blue-700 dark:text-red-500">
                      There is no cloud, it's just someone else's computer.
                    </span>{" "}
                    I have intermediate understanding of Google Cloud Platform.
                    I am experienced in deploying applications to the cloud
                    using Compute Engine (Virtual Machines), App Engine,
                    Kubernetes. Other cloud services I have used include
                    Firebase, Cloud Storage, and Netlify.
                  </p>
                </div>
                <div className="flex flex-col p-4">
                  <h3 className="font-bold dark:text-yellow-500">
                    React Native Developer
                  </h3>
                  <p className="text-sm">
                    <span className="text-blue-700 dark:text-red-500">
                      React Native is 70% React and 30% native.
                    </span>{" "}
                    With my React Knowledge, I can apply it into Native apps. I
                    have experience in building cross-platform mobile
                    applications using React Native.
                  </p>
                </div>
              </div>
            </div>
          </div>
        </section>
        <section id="skills" className="min-h-screen">
          <h3 className="font-bold mb-4 dark:text-yellow-500 text-2xl">
            Skills and Experiences
          </h3>
          <div className="flex flex-col md:flex-row items-center">
            <div className="basis-1/2">
              <h3 className="font-bold mb-4 dark:text-yellow-500 text-2xl">
                Skills
              </h3>
              <motion.div
                animate={{ x: 0 }}
                transition={{
                  duration: 2,
                  x: { duration: 1 },
                  ease: "linear",
                }}
                className=" flex flex-wrap gap-10 justify-center py-14"
              >
                {images.map((image) => (
                  <Image
                    src={image}
                    alt={`${image} logo`}
                    width={64}
                    height={64}
                    className="rounded-full bg-blue-200 hover:bg-white cursor-pointer
                  dark:hover:bg-yellow-500 dark:bg-gray-900  p-2"
                  />
                ))}
              </motion.div>
            </div>
            <div className="basis-1/2 flex flex-col flex-wrap gap-y-3 px-14 py-6 dark:text-gray-300">
              <h3 className="font-bold mb-4 dark:text-yellow-500 text-2xl">
                Experience
              </h3>
              <div>
                <p className="font-bold">Self-Employed</p>
                <p>Freelance Writing</p>
                <p>Dec 2017 - Present</p>
                <div>
                  <p className="font-bold">Responsibilities</p>
                  <ul className="list-disc">
                    <li>
                      Write SEO content for various companies including blogs,
                      landing pages, Geo and Niche silos, Press Releases, and
                      more.
                    </li>
                  </ul>
                </div>
              </div>
              <div>
                <p className="font-bold">Pawa IT Solutions</p>
                <p>Sales Associate</p>
                <p>Apr 2022 - Sep 2022</p>
                <div>
                  <p className="font-bold">Responsibilities</p>
                  <ul className="list-disc">
                    <li>
                      Lead data acquisition, collection, collation, and analysis
                      for key accounts
                    </li>
                    <li>Email-based inbound and outbound lead management</li>
                    <li>
                      Analysing internal data across the company website across
                      Google Analytics and Webmaster.
                    </li>
                  </ul>
                </div>
              </div>
            </div>
          </div>
        </section>
        <section id="portfolio" className="min-h-screen">
          <h1 className="font-bold text-2xl p-3 dark:text-yellow-500">
            Portfolio
          </h1>
          <div className="flex flex-wrap gap-4">
            <div className="p-4 shadow-xl rounded-md dark:bg-slate-900  dark:text-gray-300 bg-[#fcfcfc] w-[280px]">
              <Image src={about4} alt="about-4" width={400} height={300} />
              <p className="font-bold my-2">Just A Vision</p>
              <p className="my-2">
                This is a full-stack application for an active organization. The
                project displays my knowledge on front-end with layouts and
                wonderful designs. Material-UI and Tailwind were heavily used.
              </p>
              <p className="font-bold">Technologies used:</p>
              <p>React, Typescript, Node.JS, MongoDB, TailwindCSS</p>
              <div className="flex justify-evenly my-4">
                <button className="bg-emerald-300 px-2 rounded-full shadow-xl">
                  <Link href="https://justavision.netlify.app" target="_blank">
                    Live Site
                  </Link>
                </button>
                <button className="bg-black px-2 rounded-full shadow-xl">
                  <Link
                    href="https://github.com/Kibuye24/jav"
                    target="_blank"
                    className="text-white"
                  >
                    Github
                  </Link>
                </button>
              </div>
            </div>
            <div className="p-4 shadow-xl rounded-md dark:bg-slate-900  dark:text-gray-300 bg-[#fcfcfc] w-[280px]">
              <Image src={about4} alt="about-4" width={400} height={300} />
              <p className="font-bold my-2">Property CRM</p>
              <p className="my-2">
                This project is a CRM of a real estate company. It is a
                full-stack application with focus on authentication and Restful
                API's (CRUD operations)
              </p>
              <p className="font-bold">Technologies used:</p>
              <p>React, Typescript, Node.JS, MongoDB, MaterialUI</p>
              <div className="flex justify-evenly my-4">
                <button className="bg-emerald-300 px-2 rounded-full shadow-xl">
                  <Link
                    href="https://propertiescrm.netlify.app"
                    target="_blank"
                  >
                    Live Site
                  </Link>
                </button>
                <button className="bg-black px-2 rounded-full shadow-xl">
                  <Link
                    href="https://github.com/Kibuye24/property_crm"
                    target="_blank"
                    className="text-white"
                  >
                    Github
                  </Link>
                </button>
              </div>
            </div>
            <div className="p-4 shadow-xl rounded-md dark:bg-slate-900  dark:text-gray-300 bg-[#fcfcfc] w-[280px]">
              <Image src={about4} alt="about-4" width={400} height={300} />
              <p className="font-bold my-2">My Movie Info</p>
              <p className="my-2">
                Are you even a developer if you haven't consumed the TMDB APi?
                Here I have used the TMDB API to build a light-weight movie info
                app. The app focuses on asyncronous Javascript and fetch and
                Axios API's.
              </p>
              <p className="font-bold">Technologies used:</p>
              <p>NextJS, Javascript, Postman, TMDB API</p>
              <div className="flex justify-evenly my-4">
                <button className="dark:bg-red-400 bg-emerald-300 px-2 rounded-full shadow-xl">
                  <Link
                    href="https://my-movie-info-pearl.vercel.app"
                    target="_blank"
                  >
                    Live Site
                  </Link>
                </button>
                <button className="bg-black px-2 rounded-full shadow-xl">
                  <Link
                    href="https://github.com/Kibuye24/my-movie-info"
                    target="_blank"
                    className="text-white"
                  >
                    Github
                  </Link>
                </button>
              </div>
            </div>
            <div className="p-4 shadow-xl rounded-md dark:bg-slate-900  dark:text-gray-300 bg-[#fcfcfc] w-[280px]">
              <Image src={about4} alt="about-4" width={400} height={300} />
              <p className="font-bold my-2">Blog Application</p>
              <p className="my-2">
                This is a full-stack application where I dive into the world of
                GraphQL. The project displays knowledge in GraphQl, Headless CMS
                in GraphCMS and making queries. In this project, I use Axios for
                API calls.
              </p>
              <p className="font-bold">Technologies used:</p>
              <p>NextJS, Javascript, GraphQL, GraphCMS</p>
              <div className="flex justify-evenly my-4">
                <button className="dark:bg-red-400 bg-emerald-300 px-2 rounded-full shadow-xl">
                  <Link
                    href="https://blog-application-sigma.vercel.app/"
                    target="_blank"
                  >
                    Live Site
                  </Link>
                </button>
                <button className="bg-black px-2 rounded-full shadow-xl">
                  <Link
                    href="https://github.com/Kibuye24/blog_application"
                    target="_blank"
                    className="text-white"
                  >
                    Github
                  </Link>
                </button>
              </div>
            </div>
          </div>
        </section>
        <section id="contact" className="h-screen mt-10">
          <h1 className="font-bold text-2xl p-3 dark:text-yellow-500">
            Contact Me
          </h1>
          <form className="flex flex-col bg-[#fcfcfc] dark:bg-slate-900 rounded-lg shadow-xl p-10 dark:text-gray-300">
            <div className="w-full flex flex-col">
              <label htmlFor="name" className="m-2">
                Name
              </label>
              <input
                type="text"
                id="name"
                placeholder="Your Name"
                className="p-2 bg-blue-100 rounded-lg"
                onChange={nameEl}
              />
            </div>
            <div className="w-full flex flex-col">
              <label htmlFor="email" className="m-2">
                Email
              </label>
              <input
                type="email"
                id="email"
                placeholder="Your Email"
                className="p-2 bg-blue-100 rounded-lg"
                onChange={emailEl}
              />
            </div>
            <div className="w-full flex flex-col">
              <label htmlFor="message" className="m-2">
                Message
              </label>
              <textarea
                name="message"
                id="message"
                placeholder="Your Message"
                className="p-2 bg-blue-100 rounded-lg"
                onChange={messageEl}
              />
            </div>
            <div>
              <Link
                href={
                  "mailto:joshkibbz@gmail.com?body=Hello, my name is ...." +
                  name +
                  message
                }
              >
                <button className="w-full rounded-md p-2 mt-4 bg-blue-700">
                  Send
                </button>
              </Link>
            </div>
          </form>
        </section>
        <div className=" shadow-xl rounded-lg dark:bg-slate-800 bg-[#fcfcfc] p-2 fixed flex flex-col bottom-4 left-0 sm:left-3 ">
          <button>
            <Link
              href="https://www.linkedin.com/in/joshua-kibuye-2ab4b6140/"
              target="_blank"
            >
              <AiFillLinkedin className="text-blue-700 my-2" />
            </Link>
          </button>
          <button>
            <Link href="https://github.com/Kibuye24" target="_blank">
              <AiFillGithub className="text-black my-2" />
            </Link>
          </button>
          <button>
            <Link href="https://twitter.com/KibuyeJosh" target="_blank">
              <AiFillTwitterCircle className="text-blue-300 my-2" />
            </Link>
          </button>
        </div>
      </main>
    </div>
  );
}
